# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 735dbe605193920877f7aec5b0c656675608c0409dd2b767f5076cd324773012a16a4dae01c3254cb8a98459451729f6b83896b4bf992c752ee1917e70f3a28f

test:
  secret_key_base: 530222aec07cd0790b61790351b3d2f85504a759d8c3066a682872080616bbbb1df947fb296c261de6777df73c2c80a8161827fee332ff126a693113582bc4dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
